### ISSUE TITLE
This is so flawed. You can't make a regex without escaping it.

### ISSUE THREAD

**Issue by felixhao28** [mim-Armand/replaceAll-Shim#1]
Try this:

```
"aabbcc".replaceAll(".", "xx");
```

Expected: `aaxxxxcc`

Actual: `xxxxxxxxxxxx`

**Comment by mim-Armand** [comment]
This was a simple implementation for a specific project, and it worked great for that, if you think you can make improvements go ahead and make a PR, otherwise don't complain! 
In general, it's not only rude, but also counter-productive to go to some random repository and open an issue starting with "This is so flawed. You can't do this or that"! you see that I obviously can! lol 🤦‍♂️
